mysql:
  host: ""
  port: 3306
  dbname: ""
  user: ""
  pass: ""
  prefix: "dstat_"
clean:
  days: 180
  auto: false
  commands:
    - "say Player $player_name$ has been removed."
debug: false
dbversion: 1